import { Rubik } from "next/font/google";
import "./globals.css";

const rubik = Rubik({ subsets: ["arabic"] })

export const metadata = {
  title: "TelePort",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar">
      <body className={`${rubik.className} bg-[#FBFBFB] h-[2000px]  `}>
        {children}
      </body>
    </html>
  );
}
